# Generated by Django 5.2.5 on 2025-09-08 17:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_product_price_large_product_price_medium'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='price_large',
        ),
        migrations.RemoveField(
            model_name='product',
            name='price_medium',
        ),
    ]
