# Generated by Django 5.2.5 on 2025-09-08 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_remove_product_price_large_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='price_large',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='product',
            name='price_medium',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
